productos = [
    { "id": 1, "nombre": "Laptop", "precio": 800.0, "stock": 5, "disponible": True },
    { "id": 2, "nombre": "Mouse", "precio": 20.0, "stock": 15, "disponible": True },
    { "id": 3, "nombre": "Teclado", "precio": 50.0, "stock": 10, "disponible": True },
    { "id": 4, "nombre": "Monitor", "precio": 200.0, "stock": 8, "disponible": True },
    { "id": 5, "nombre": "Silla Gamer", "precio": 150.0, "stock": 3, "disponible": True },
    { "id": 6, "nombre": "Auriculares", "precio": 40.0, "stock": 12, "disponible": True },
    { "id": 7, "nombre": "Micrófono", "precio": 70.0, "stock": 7, "disponible": True },
    { "id": 8, "nombre": "Webcam", "precio": 90.0, "stock": 6, "disponible": True },
    { "id": 9, "nombre": "Smartphone", "precio": 600.0, "stock": 4, "disponible": True },
    { "id": 10, "nombre": "Tablet", "precio": 350.0, "stock": 5, "disponible": True },
    { "id": 11, "nombre": "Disco Duro Externo", "precio": 100.0, "stock": 10, "disponible": True },
    { "id": 12, "nombre": "Cargador USB-C", "precio": 25.0, "stock": 20, "disponible": True },
    { "id": 13, "nombre": "Router WiFi", "precio": 120.0, "stock": 5, "disponible": True },
    { "id": 14, "nombre": "Power Bank", "precio": 45.0, "stock": 15, "disponible": True },
    { "id": 15, "nombre": "Smartwatch", "precio": 180.0, "stock": 6, "disponible": True },
    { "id": 16, "nombre": "Tarjeta Gráfica", "precio": 400.0, "stock": 2, "disponible": True },
    { "id": 17, "nombre": "Placa Base", "precio": 220.0, "stock": 4, "disponible": True },
    { "id": 18, "nombre": "Memoria RAM 16GB", "precio": 90.0, "stock": 10, "disponible": True },
    { "id": 19, "nombre": "Procesador Intel i7", "precio": 320.0, "stock": 3, "disponible": True },
    { "id": 20, "nombre": "Fuente de Poder 600W", "precio": 80.0, "stock": 7, "disponible": True },
    { "id": 21, "nombre": "SSD 1TB", "precio": 150.0, "stock": 8, "disponible": True },
    { "id": 22, "nombre": "Cámara de Seguridad", "precio": 110.0, "stock": 9, "disponible": True },
    { "id": 23, "nombre": "Adaptador Bluetooth", "precio": 30.0, "stock": 18, "disponible": True },
    { "id": 24, "nombre": "Base Refrigerante para Laptop", "precio": 35.0, "stock": 12, "disponible": True },
    { "id": 25, "nombre": "Cable HDMI", "precio": 15.0, "stock": 25, "disponible": True },
    { "id": 26, "nombre": "Impresora Multifuncional", "precio": 140.0, "stock": 4, "disponible": True },
    { "id": 27, "nombre": "Scanner", "precio": 95.0, "stock": 7, "disponible": True },
    { "id": 28, "nombre": "Lámpara LED para Escritorio", "precio": 60.0, "stock": 10, "disponible": True },
    { "id": 29, "nombre": "Router Mesh", "precio": 220.0, "stock": 3, "disponible": True },
    { "id": 30, "nombre": "Soporte para Monitor", "precio": 50.0, "stock": 11, "disponible": True },
    { "id": 31, "nombre": "Joystick para PC", "precio": 75.0, "stock": 6, "disponible": True },
    { "id": 32, "nombre": "Disco Duro Interno 2TB", "precio": 130.0, "stock": 7, "disponible": True },
    { "id": 33, "nombre": "Tablet Gráfica", "precio": 300.0, "stock": 4, "disponible": True },
    { "id": 34, "nombre": "Cable Ethernet CAT6", "precio": 10.0, "stock": 30, "disponible": True },
    { "id": 35, "nombre": "Smart TV 40 pulgadas", "precio": 500.0, "stock": 5, "disponible": True },
    { "id": 36, "nombre": "Proyector HD", "precio": 350.0, "stock": 3, "disponible": True },
    { "id": 37, "nombre": "Dispositivo de Streaming", "precio": 120.0, "stock": 8, "disponible": True },
    { "id": 38, "nombre": "Teclado Mecánico RGB", "precio": 90.0, "stock": 7, "disponible": True },
    { "id": 39, "nombre": "Ratón Inalámbrico", "precio": 35.0, "stock": 15, "disponible": True },
    { "id": 40, "nombre": "Micrófono USB Profesional", "precio": 110.0, "stock": 5, "disponible": True },
    { "id": 41, "nombre": "Alfombrilla Gamer XL", "precio": 25.0, "stock": 20, "disponible": True },
    { "id": 42, "nombre": "VR Headset", "precio": 500.0, "stock": 2, "disponible": True },
    { "id": 43, "nombre": "Smart Speaker", "precio": 80.0, "stock": 10, "disponible": True },
    { "id": 44, "nombre": "Control Remoto Universal", "precio": 25.0, "stock": 18, "disponible": True },
    { "id": 45, "nombre": "Hub USB 3.0", "precio": 35.0, "stock": 22, "disponible": True },
    { "id": 46, "nombre": "Cable USB-C a Lightning", "precio": 20.0, "stock": 30, "disponible": True },
    { "id": 47, "nombre": "Almacenamiento en Red NAS 4TB", "precio": 450.0, "stock": 4, "disponible": True },
    { "id": 48, "nombre": "Batería para Laptop", "precio": 80.0, "stock": 8, "disponible": True },
    { "id": 49, "nombre": "Teclado Bluetooth", "precio": 60.0, "stock": 9, "disponible": True },
    { "id": 50, "nombre": "Filtro de Línea", "precio": 30.0, "stock": 15, "disponible": True },
]
